export const portfolioData = {
  brand: 'elyel.dev',
  profileImage: '/elyel-dev.JPG',
  ui: {
    en: {
      nav: [
        { id: 'about', label: 'About' },
        { id: 'experience', label: 'Experience' },
        { id: 'skills', label: 'Skills' },
        { id: 'projects', label: 'Projects' },
        { id: 'contact', label: 'Contact' },
      ],
      ctaExperience: 'View Experience',
      ctaContact: 'Contact Me',
      selectedProjects: 'Selected Projects',
      contextLabel: 'Context:',
      impactLabel: 'Impact:',
      sectionLabels: {
        about: 'About',
        experience: 'Experience',
        skills: 'Skills',
        differentials: 'Differentials',
        contact: 'Contact',
      },
      localeToggle: 'PT-BR',
      themeLight: 'Light',
      themeDark: 'Dark',
      profileAlt: 'Rodrigo Elyel profile photo',
      photoTitle: 'Education',
      photoText: 'Academic background and contact details.',
      photoSummary: 'Education',
      phoneLabel: 'Phone',
      emailLabel: 'Email',
      addressLabel: 'Address',
      linkedinLabel: 'LinkedIn',
      contactButton: 'Get in Touch',
    },
    pt: {
      nav: [
        { id: 'about', label: 'Sobre' },
        { id: 'experience', label: 'Experiência' },
        { id: 'skills', label: 'Skills' },
        { id: 'projects', label: 'Projetos' },
        { id: 'contact', label: 'Contato' },
      ],
      ctaExperience: 'Ver Experiência',
      ctaContact: 'Entrar em Contato',
      selectedProjects: 'Projetos em Destaque',
      contextLabel: 'Contexto:',
      impactLabel: 'Impacto:',
      sectionLabels: {
        about: 'Sobre',
        experience: 'Experiência',
        skills: 'Skills',
        differentials: 'Diferenciais',
        contact: 'Contato',
      },
      localeToggle: 'EN-US',
      themeLight: 'Claro',
      themeDark: 'Escuro',
      profileAlt: 'Foto de perfil de Rodrigo Elyel',
      photoTitle: 'Formações',
      photoText: 'Formação acadêmica e dados de contato.',
      photoSummary: 'Formações',
      phoneLabel: 'Telefone',
      emailLabel: 'Email',
      addressLabel: 'Endereço',
      linkedinLabel: 'LinkedIn',
      contactButton: 'Fale Comigo',
    },
  },
  translations: {
    en: {
      role: 'Mid-Level Software Engineer',
      location: 'Brazil · Open to international remote opportunities',
      hero: {
        headline: 'Rodrigo Elyel Mid-Level Software Engineer',
        subheadline:
          'Full-stack and mobile developer focused on performance, clean architecture, and delivering results that matter.',
        highlights: [
          'Worked on global projects for MODEC, an international oil and gas company',
          'Critical backlog reduced from 70 to fewer than 10 tickets in 6 months',
          'Legacy front-end rebuilt in React.js with higher performance and better user experience',
          'Two consecutive promotions and top evaluation scores',
        ],
      },
      about: [
        'Rodrigo Elyel is a Mid-Level Software Engineer with experience in full-stack and mobile development, working on global projects for international companies.',
        'Strong background in React, React Native, and ASP.NET, with a proven track record of reducing critical backlogs, modernizing legacy systems, and providing technical leadership to development teams.',
        'Recognized for fast learning, technical autonomy, and mentoring skills, achieving consecutive promotions through high performance and project impact.',
      ],
      experience: [
        {
          title: 'Full-Stack Developer',
          company: 'Visagio / V(dev) - Rio de Janeiro, Brazil',
          period: 'Apr 2023 - Present',
          bullets: [
            'Worked, as a Visagio software developer, on global projects for MODEC, an international oil and gas company, supporting onshore and offshore users in its system.',
            'Reduced a critical backlog from 70 to fewer than 10 tickets within 6 months, leading to contract expansion into additional modules.',
            'Rebuilt a legacy front-end in React.js, delivering higher performance and improved user experience.',
            'Acted as Tech Lead for a 4-person team, becoming a key technical reference for both client and internal teams.',
            'Mentored junior developers by creating individual development plans and supported project reviews to ensure adherence to quality standards.',
            'Recognized for performance with two consecutive promotions and top evaluation scores.',
          ],
        },
        {
          title: 'Mobile Developer',
          company: 'Grupo Seven - Uberlândia, Brazil',
          period: 'Sep 2021 - Mar 2023',
          bullets: [
            'Started as a React Native mobile developer, initially focusing on bug fixing and small improvements, gradually gaining autonomy.',
            'Took ownership of new feature implementations as trust with the Tech Lead increased, contributing to continuous app development.',
            'Led a full app rebuild from scratch in React Native, fully integrated with the existing backend, delivered in 4 months with high performance and improved usability.',
            'Maintained the new application and provided support to other developers in web development using React.js, fostering cross-team collaboration.',
          ],
        },
      ],
      skills: {
        Languages: ['JavaScript', 'TypeScript', 'C#', 'Python'],
        Frontend: ['HTML', 'CSS', 'React.js', 'CSHTML (Razor)'],
        Backend: ['ASP.NET', 'Flask'],
        Mobile: ['React Native'],
        Infrastructure: ['GitHub', 'GitLab', 'Azure'],
      },
      education: [
        'Postgraduate in Mobile Development | Federal Institute of Piauí | Apr 2023 - Oct 2024',
        'Bachelor’s Degree in Computer Science | Federal University of Piauí | Aug 2017 - Dec 2022',
      ],
      projects: [
        {
          name: 'Legacy Front-End Rebuild',
          context: 'Legacy interface was slowing delivery and hurting user trust.',
          impact: 'Migrated to React architecture with faster workflows and cleaner maintenance.',
          stack: ['React.js', 'JavaScript', 'ASP.NET'],
        },
        {
          name: 'Backlog Recovery Program',
          context: 'High-priority backlog threatened delivery pace and confidence.',
          impact: 'Structured triage and execution flow that cut critical tickets by more than 85%.',
          stack: ['React.js', 'C#', 'Azure'],
        },
        {
          name: 'Mobile App Rebuild',
          context: 'Existing app needed a full rebuild to scale features and quality.',
          impact: 'Delivered a new React Native app in 4 months with stable post-launch evolution.',
          stack: ['React Native', 'TypeScript', 'REST API'],
        },
      ],
      differentials: [
        'Proven delivery under pressure with measurable outcomes.',
        'Strong adaptability to new technologies and complex contexts.',
        'Experience in global and distributed teams.',
        'Technical leadership with hands-on execution.',
        'Focus on clean code, maintainability, and business impact.',
      ],
      contact: {
        message:
          'If you are hiring an engineer who can code, communicate, and deliver under real constraints, let\'s talk.',
        phone: '+55 86 995279594',
        email: 'rodrigoelyelcb@gmail.com',
        address: 'Rua Canadá, 995. Bairro Cidade Nova, Teresina-PI',
        linkedin: 'www.linkedin.com/in/rodrigo-elyel-developer',
      },
    },
    pt: {
      role: 'Engenheiro de Software Pleno',
      location: 'Brasil · Aberto a oportunidades internacionais remotas',
      hero: {
        headline: 'Rodrigo Elyel Engenheiro de Software Pleno',
        subheadline:
          'Desenvolvedor full-stack e mobile focado em performance, arquitetura limpa e entregas que realmente importam.',
        highlights: [
          'Atuação em projetos globais para a MODEC, empresa internacional do setor de óleo e gás',
          'Backlog crítico reduzido de 70 para menos de 10 tickets em 6 meses',
          'Front-end legado reconstruído em React.js com maior performance e melhor experiência do usuário',
          'Duas promoções consecutivas e notas altas em avaliações',
        ],
      },
      about: [
        'Rodrigo Elyel é Engenheiro de Software Pleno com experiência em desenvolvimento full-stack e mobile, atuando em projetos globais para empresas internacionais.',
        'Possui forte domínio em React, React Native e ASP.NET, com histórico de redução de backlog crítico, modernização de sistemas legados e liderança técnica de equipes.',
        'Reconhecido por rápida capacidade de aprendizado, autonomia técnica e habilidade em mentoria, foi promovido consecutivamente por alto desempenho e impacto nos projetos.',
      ],
      experience: [
        {
          title: 'Desenvolvedor Full-Stack',
          company: 'Visagio / V(dev) - Rio de Janeiro, Brasil',
          period: 'Abr 2023 - Atual',
          bullets: [
            'Atuei, como desenvolvedor da Visagio, em projetos globais para a MODEC, empresa internacional do setor de óleo e gás, com usuários onshore e offshore em seu sistema.',
            'Reduzi backlog crítico de 70 para menos de 10 tickets em 6 meses, gerando expansão do contrato da Visagio para novos módulos.',
            'Reconstruí front-end legado em React.js, entregando maior performance e melhor experiência do usuário.',
            'Atuei como Tech Lead de uma equipe de 4 pessoas, tornando-me referência técnica para clientes e times internos.',
            'Mentorei desenvolvedores juniores, auxiliando em planos de desenvolvimento individual e apoiando a avaliação de projetos para garantir padrões de qualidade da Visagio.',
            'Reconhecido pela performance com duas promoções consecutivas e notas altas em avaliações.',
          ],
        },
        {
          title: 'Desenvolvedor Mobile',
          company: 'Grupo Seven - Uberlândia, Brasil',
          period: 'Set 2021 - Mar 2023',
          bullets: [
            'Iniciei como desenvolvedor mobile em React Native, atuando na resolução de bugs e pequenas melhorias, ganhando autonomia progressivamente.',
            'Assumi a implementação de novas funcionalidades à medida que conquistava confiança do Tech Lead, contribuindo para evolução contínua do app.',
            'Liderança técnica no refactor completo do aplicativo, reconstruído do zero em React Native, integrado ao backend existente, entregue em 4 meses com alta performance e usabilidade.',
            'Atuei na sustentação do novo aplicativo e ofereci suporte a outros desenvolvedores no desenvolvimento web com React.js, promovendo colaboração entre equipes.',
          ],
        },
      ],
      skills: {
        Linguagens: ['JavaScript', 'TypeScript', 'C#', 'Python'],
        Frontend: ['HTML', 'CSS', 'React.js', 'CSHTML (Razor)'],
        Backend: ['ASP.NET', 'Flask'],
        Mobile: ['React Native'],
        Infraestrutura: ['GitHub', 'GitLab', 'Azure'],
      },
      education: [
        'Pós-Graduação em Desenvolvimento Mobile | Instituto Federal do Piauí | Abril 2023 - Outubro 2024',
        'Bacharel em Ciência da Computação | Universidade Federal do Piauí | Agosto 2017 - Dezembro 2022',
      ],
      projects: [
        {
          name: 'Rebuild de Front-End Legado',
          context: 'Uma interface legada reduzia velocidade de entrega e confiança do usuário.',
          impact: 'Migração para arquitetura React com fluxo mais rápido e manutenção mais simples.',
          stack: ['React.js', 'JavaScript', 'ASP.NET'],
        },
        {
          name: 'Recuperação de Backlog Crítico',
          context: 'O backlog de alta prioridade comprometia ritmo e previsibilidade.',
          impact: 'Estruturou triagem e execução, reduzindo tickets críticos em mais de 85%.',
          stack: ['React.js', 'C#', 'Azure'],
        },
        {
          name: 'Rebuild de Aplicativo Mobile',
          context: 'O app existente precisava ser reconstruído para escalar funcionalidades e qualidade.',
          impact: 'Nova aplicação React Native entregue em 4 meses com evolução estável no pós-lançamento.',
          stack: ['React Native', 'TypeScript', 'REST API'],
        },
      ],
      differentials: [
        'Capacidade comprovada de entregar resultado sob pressão com métricas claras.',
        'Alta adaptabilidade a novas tecnologias e contextos complexos.',
        'Experiência atuando com times globais e distribuídos.',
        'Liderança técnica com execução hands-on.',
        'Foco em código limpo, manutenção e impacto real no negócio.',
      ],
      contact: {
        message:
          'Se você busca um engenheiro que programa, se comunica bem e entrega com consistência em cenários reais, vamos conversar.',
        phone: '+55 86 995279594',
        email: 'rodrigoelyelcb@gmail.com',
        address: 'Rua Canadá, 995. Bairro Cidade Nova, Teresina-PI',
        linkedin: 'www.linkedin.com/in/rodrigo-elyel-developer',
      },
    },
  },
  socialLinks: [
    {
      label: 'LinkedIn',
      href: 'https://www.linkedin.com/in/rodrigo-elyel-developer/',
    },
    {
      label: 'Instagram',
      href: 'https://www.instagram.com/rodrigoelyel.dev/',
    },
    {
      label: 'Email',
      href: 'mailto:rodrigoelyelcb@gmail.com',
    },
    {
      label: 'WhatsApp',
      href: 'https://wa.me/5586995279594',
    },
  ],
}
